###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 15,
    "weight": 200,
    "unit": "lbs",
    "date": "01-01-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 15,
    "weight": 200,
    "unit": "lbs",
    "date": "11-13-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 15,
    "weight": 200,
    "unit": "lbs",
    "date": "11-15-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 10,
    "weight": 220,
    "unit": "lbs",
    "date": "11-18-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 10,
    "weight": 220,
    "unit": "lbs",
    "date": "11-20-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 10,
    "weight": 220,
    "unit": "lbs",
    "date": "11-22-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squats",
    "reps": 20,
    "weight": 250,
    "unit": "lbs",
    "date": "11-11-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squats",
    "reps": 20,
    "weight": 250,
    "unit": "lbs",
    "date": "11-13-21"
}


###npm
GET http://localhost:3000/exercises HTTP/1.1


###

PUT http://localhost:3000/exercises/61a76bb6eaf6f87f8af9783b HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 20,
    "weight": 200,
    "unit": "lbs",
    "date": "11-11-21"
}


###
DELETE http://localhost:3000/exercises/61a76bbbeaf6f87f8af9783d HTTP/1.1
